export const CAR_BRANDS = [
  { id: 'toyota', name: 'Toyota', icon: 'T' },
  { id: 'honda', name: 'Honda', icon: 'H' },
  { id: 'mazda', name: 'Mazda', icon: 'M' },
  { id: 'nissan', name: 'Nissan', icon: 'N' },
  { id: 'mitsubishi', name: 'Mitsubishi', icon: 'Mi' },
  { id: 'isuzu', name: 'Isuzu', icon: 'I' },
  { id: 'suzuki', name: 'Suzuki', icon: 'S' },
  { id: 'ford', name: 'Ford', icon: 'F' },
  { id: 'chevrolet', name: 'Chevrolet', icon: 'C' },
  { id: 'mg', name: 'MG', icon: 'MG' },
  { id: 'mercedes', name: 'Mercedes-Benz', icon: 'MB' },
  { id: 'bmw', name: 'BMW', icon: 'BM' },
  { id: 'audi', name: 'Audi', icon: 'Au' },
  { id: 'lexus', name: 'Lexus', icon: 'L' },
  { id: 'volvo', name: 'Volvo', icon: 'V' },
  { id: 'porsche', name: 'Porsche', icon: 'P' },
  { id: 'subaru', name: 'Subaru', icon: 'Su' },
  { id: 'gwm', name: 'GWM', icon: 'G' },
  { id: 'byd', name: 'BYD', icon: 'BY' },
  { id: 'neta', name: 'Neta', icon: 'Ne' },
  { id: 'ora', name: 'ORA', icon: 'O' },
  { id: 'other', name: 'อื่นๆ', icon: '?' },
];

export const CAR_MODELS: Record<string, string[]> = {
  toyota: ['Yaris', 'Vios', 'Corolla Altis', 'Corolla Cross', 'Camry', 'C-HR', 'Fortuner', 'Hilux Revo', 'Hilux Vigo', 'Innova', 'Veloz', 'Rush', 'Avanza', 'Land Cruiser', 'GR86', 'Supra', 'bZ4X'],
  honda: ['City', 'Civic', 'Accord', 'Jazz', 'HR-V', 'CR-V', 'BR-V', 'WR-V', 'e:N1'],
  mazda: ['Mazda2', 'Mazda3', 'CX-3', 'CX-5', 'CX-30', 'CX-60', 'BT-50', 'MX-5'],
  nissan: ['Almera', 'Note', 'Kicks', 'X-Trail', 'Navara', 'Terra', 'Leaf'],
  mitsubishi: ['Attrage', 'Mirage', 'Xpander', 'Pajero Sport', 'Triton', 'Outlander'],
  isuzu: ['D-Max', 'MU-X'],
  suzuki: ['Swift', 'Ciaz', 'Ertiga', 'XL7', 'Jimny', 'Carry'],
  ford: ['Ranger', 'Everest', 'Territory'],
  chevrolet: ['Colorado', 'Trailblazer', 'Captiva'],
  mg: ['MG3', 'MG5', 'ZS', 'HS', 'EP', 'MG4', 'Extender'],
  mercedes: ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'GLA', 'GLC', 'GLE', 'GLS', 'CLA', 'AMG GT'],
  bmw: ['1 Series', '3 Series', '5 Series', '7 Series', 'X1', 'X3', 'X5', 'X7', 'iX', 'i4'],
  audi: ['A3', 'A4', 'A6', 'Q3', 'Q5', 'Q7', 'e-tron'],
  lexus: ['CT', 'IS', 'ES', 'NX', 'RX', 'UX', 'LX'],
  volvo: ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V60'],
  porsche: ['Cayenne', 'Macan', 'Panamera', '911', 'Taycan'],
  subaru: ['XV', 'Forester', 'Outback', 'BRZ', 'WRX'],
  gwm: ['HAVAL H6', 'HAVAL JOLION', 'ORA Good Cat', 'Tank 300'],
  byd: ['Atto 3', 'Dolphin', 'Seal', 'Han', 'Tang'],
  neta: ['V-II', 'X'],
  ora: ['Good Cat'],
  other: [],
};

export const CAR_COLORS = [
  { id: 'black', name: 'ดำ', hex: '#1a1a1a' },
  { id: 'white', name: 'ขาว', hex: '#f5f5f5' },
  { id: 'silver', name: 'เงิน', hex: '#c0c0c0' },
  { id: 'gray', name: 'เทา', hex: '#808080' },
  { id: 'red', name: 'แดง', hex: '#cc0000' },
  { id: 'blue', name: 'น้ำเงิน', hex: '#003399' },
  { id: 'brown', name: 'น้ำตาล', hex: '#8B4513' },
  { id: 'green', name: 'เขียว', hex: '#2d6a2d' },
  { id: 'orange', name: 'ส้ม', hex: '#e06000' },
  { id: 'yellow', name: 'เหลือง', hex: '#d4a900' },
];


// Kept for potential future API integration
const _MODEL_FAMILY_MAP: Record<string, string> = {
  'yaris': 'yaris',
  'vios': 'vios',
  'corolla altis': 'corolla',
  'corolla cross': 'corolla-cross',
  'camry': 'camry',
  'c-hr': 'c-hr',
  'fortuner': 'fortuner',
  'hilux revo': 'hilux',
  'hilux vigo': 'hilux',
  'innova': 'innova',
  'veloz': 'veloz',
  'rush': 'rush',
  'avanza': 'avanza',
  'land cruiser': 'land-cruiser',
  'gr86': '86',
  'supra': 'supra',
  'bz4x': 'bz4x',
  'city': 'city',
  'civic': 'civic',
  'accord': 'accord',
  'jazz': 'jazz',
  'hr-v': 'hr-v',
  'cr-v': 'cr-v',
  'br-v': 'br-v',
  'wr-v': 'wr-v',
  'e:n1': 'e-ny1',
  'mazda2': '2',
  'mazda3': '3',
  'cx-3': 'cx-3',
  'cx-5': 'cx-5',
  'cx-30': 'cx-30',
  'cx-60': 'cx-60',
  'bt-50': 'bt-50',
  'mx-5': 'mx-5',
  'almera': 'almera',
  'note': 'note',
  'kicks': 'kicks',
  'x-trail': 'x-trail',
  'navara': 'navara',
  'terra': 'terra',
  'leaf': 'leaf',
  'attrage': 'attrage',
  'mirage': 'mirage',
  'xpander': 'xpander',
  'pajero sport': 'pajero-sport',
  'triton': 'l200',
  'outlander': 'outlander',
  'd-max': 'd-max',
  'mu-x': 'mu-x',
  'swift': 'swift',
  'ciaz': 'ciaz',
  'ertiga': 'ertiga',
  'xl7': 'xl7',
  'jimny': 'jimny',
  'carry': 'carry',
  'ranger': 'ranger',
  'everest': 'everest',
  'territory': 'territory',
  'colorado': 'colorado',
  'trailblazer': 'trailblazer',
  'captiva': 'captiva',
  'mg3': '3',
  'mg5': '5',
  'zs': 'zs',
  'hs': 'hs',
  'ep': 'ep',
  'mg4': '4',
  'extender': 'extender',
  'a-class': 'a-class',
  'c-class': 'c-class',
  'e-class': 'e-class',
  's-class': 's-class',
  'gla': 'gla',
  'glc': 'glc',
  'gle': 'gle',
  'gls': 'gls',
  'cla': 'cla',
  'amg gt': 'amg-gt',
  '1 series': '1-series',
  '3 series': '3-series',
  '5 series': '5-series',
  '7 series': '7-series',
  'x1': 'x1',
  'x3': 'x3',
  'x5': 'x5',
  'x7': 'x7',
  'ix': 'ix',
  'i4': 'i4',
  'a3': 'a3',
  'a4': 'a4',
  'a6': 'a6',
  'q3': 'q3',
  'q5': 'q5',
  'q7': 'q7',
  'e-tron': 'e-tron',
  'ct': 'ct',
  'is': 'is',
  'es': 'es',
  'nx': 'nx',
  'rx': 'rx',
  'ux': 'ux',
  'lx': 'lx',
  'xc40': 'xc40',
  'xc60': 'xc60',
  'xc90': 'xc90',
  's60': 's60',
  's90': 's90',
  'v60': 'v60',
  'cayenne': 'cayenne',
  'macan': 'macan',
  'panamera': 'panamera',
  '911': '911',
  'taycan': 'taycan',
  'xv': 'xv',
  'forester': 'forester',
  'outback': 'outback',
  'brz': 'brz',
  'wrx': 'wrx',
  'haval h6': 'h6',
  'haval jolion': 'jolion',
  'ora good cat': 'good-cat',
  'tank 300': 'tank-300',
  'atto 3': 'atto-3',
  'dolphin': 'dolphin',
  'seal': 'seal',
  'han': 'han',
  'tang': 'tang',
  'v-ii': 'v-ii',
  'x': 'x',
  'good cat': 'good-cat',
};

export function getCarFallbackUrl(type: 'sedan' | 'suv' | 'pickup' | 'motorcycle' = 'sedan'): string {
  return `/cars/fallback-${type}.svg`;
}
